### ISSUE TITLE
Mark highlights of the stream, to be viewable on the website.

### ISSUE THREAD

**Issue by pajlada** [pajlada/tyggbot#23]
## Command
!add highlight
Optional arguments
--id ID of existing highlight to edit
--offset Amount of "back in time" to offset the highlight with

Positional argument:
Tag/Description

### tb_stream
id, auto increment, primary key, int
title, varchar, 256. max length for twitch titles right now seem to be 140 but yolo
stream_start, datetime, time for when the stream started. When the stream is started, this should be adjusted based on the initial "created_at" attribute of the API call which we use to check if the stream is live or not.
stream_end, datetime, time for when the stream is ended. This should be the timestamp when the stream hs first seen as "offline", not after the X amount of retries have gotten the "offline" mark in a row.

### tb_stream_chunk
*When a new chunk is detected (due to the change in _id), try to check if there's a video ID available here: https://api.twitch.tv/kraken/channels/strifecro/videos?limit=10&broadcasts=true
If there is no video with the same broadcast id there yet, set it to null.
Upon checking stream status, if the current chunk url is null, this API should be checked again.*
id, auto increment, primary key, int
stream_id, foreign key linking back to a tb_stream
broadcast_id, unique ID, as seen in https://api.twitch.tv/kraken/streams/strifecro. use _id there
video_url, varchar, 128, nullable
chunk_start, datetime
chunk_end, datetime

### tb_stream_chunk_highlight
id, auto increment, primary key, int
chunk_id, foreign key linking back to a tb_stream
created_at, datetime, timestamp of when the highlight was created
highlight_offset, datetime
description, text, nullable

## Code structure
another model
should be StreamManager
which starts an execute_every for the stream_check interval (by default, this is currently 20).
Maybe StreamManager should not keep a permanent session, as the DB requests should very seldomly be made.

## Web part
There should be an entire section for highlights.
How should we list them?
Right now we fetch all chunks, in descending order, and just list all highlights.
In the future, we should probably fetch, along with the video url, we fetch the preview image as well.

## TODO for later
 - [x] Fetch preview image for each chunk as well
 - [x] Improve the listing on /highlights so it looks decent
 - [x] Add some sort of paging on the /highlights page
 - [x] Run bot before stream goes live, go live until video url is fetched, then go offline for a second, and go live again so a new chunk is started, make sure it can fetch the video url for that as well.
 - [x] ask ilisha how she wants the offset to work. Should the default be 40 seconds back in the vod?
 - [x] look into delaying the video_url fetching, by 10 minutes or something. should it be run in a separate thread? This will be apparent during the test mentioned above

**Comment by pajlada** [comment]
Base feature complete. Ask the streams the bot runs in whether there's something missing or not.
